sudo: false

language: node_js

node_js:
  - 10.16.3

install:
  - npm ci
  
script:
  - npm test
  - npm start 
  
deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master   